apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
  annotations:
    # Enable sticky sessions for WebSockets
    service.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  selector:
    app: delivery-service
  ports:
  - port: 3004
    targetPort: 3004
    name: http
  type: ClusterIP