apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded value of your MongoDB URI
  # Example: echo -n "mongodb://username:password@mongodb-host:27017/dbname" | base64
  mongodb-uri: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGItaG9zdDoyNzAxNy9kYm5hbWU=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # Base64 encoded value of your JWT secret
  # Example: echo -n "your-jwt-secret-key" | base64
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleQ==
